name: HungerDisabler
version: 1.0.0
author: Matthww
api: [3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.1]
description: Disable hunger!
main: Matthww\HungerDisabler\HungerDisabler
